=== redhog/DemoWave/DTD/law/0.1.0.dtd
<!ELEMENT h ( #PCDATA ) >

<!ELEMENT law ( p+ ) >
<!ATTLIST law title CDATA #IMPLIED >

<!ELEMENT p ( #PCDATA | h | p )* >
<!ATTLIST p delete CDATA #IMPLIED >
<!ATTLIST p id NMTOKEN #IMPLIED >

=== redhog/DemoWave/help/demo.law.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE law PUBLIC "DemoWave//law//0.1.0" "/home/redhog/Projects/DemoWave/DemoWave/DTD/law/0.1.0.dtd">
<law>
 <p>
  <h>para 1</h>
  text 1
  <p>
   <h>para 1.1</h>
   text 1.1
  </p>
  <p>
   <h>para 1.2</h>
   text 1.2
  </p>
 </p>
 <p>
  <h>para 2</h>
  text 2
 </p>
</law>

=== redhog/DemoWave/help/demo-edit.law.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE law PUBLIC "DemoWave//law//0.1.0" "/home/redhog/Projects/DemoWave/DemoWave/DTD/law/0.1.0.dtd">
<law title="Some changes">
 <p id='47'>
  <p id='11.2'>
   <h>para 47.11.2</h>
   text 47.11.2
  </p>
  <p>
   <h>para 47.11.something</h>
   text 47.11.something greater than 2
  </p>
 </p>
 <p>
  <h>para something</h>
  text something greater than 47
 </p>
 <p id='32.23.445' delete='' />
</law>
